services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/mydatabase?authSource=admin
      NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

volumes:
  mongo_data: